name: libuca with dependencies via conan

on:
  push:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Conan
        run: python -m pip install "conan>=2.10,<3"
      - name: Create package
        run: conan create -pr:a conan/windows_release . --build=missing
