name: libuca tests

on:
  push:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: get conan
        uses: turtlebrowser/get-conan@v1.0
      - name: create conan profile
        run: conan profile new default --detect
      - name: build
        run: |
          mkdir build
          cd build
          conan install .. --build missing
          cmake ..
          cmake --build .
          cmake --install .
      - name: run test-mock
        run: |
          pwd
          dir
          build\test\test-mock.exe
      - name: run test-ring-buffer
        run: |
          build\test\test-ring-buffer